### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by sprajapat770** [develodesign/magento-gitpod#10]
#24 0.199 /bin/sh: 1: cannot create /etc/php/8.1/mods-available/xdebug.ini: Permission denied
#24 ERROR: process "/bin/sh -c echo \"xdebug.remote_enable=on\" >> /etc/php/${PHP_VERSION}/mods-available/xdebug.ini" did not complete

**Comment by collymore** [comment]
@sprajapat770 this is fixed now. There was an update to the base docker image
