### ISSUE TITLE
Nginx does not start

### ISSUE THREAD

**Issue by robhuijben** [develodesign/magento-gitpod#20]
Hi, I was trying to start a Gitpod workspace but unfortunately ran into an issue where Nginx doesn't seem to start and hangs on `start nginx nginx`.

This happens after these commands:

```
gitpod /workspace/magento-gitpod (main) $  HISTFILE=/workspace/.gitpod/cmd-2 history -r; {
> gp ports await 3306 && sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/nginx/nginx.conf && service nginx start
> }
Awaiting port 3306... ok
 * Starting nginx nginx   
```

In the terminal I also noticed the following issues:

```
============ 1. Install Magento if required ==========
mysql: [Warning] Using a password on the command line interface can be insecure.
Could not open input file: bin/magento
================ 2. INSTALL DB ===============
----------------------------------------------
======= 3. INSTALL MAGENTO ENV & CONFIG ======
-----------------------------------------------
==== 4. CONFIGURATION (config:set) CHANGES ====
Could not open input file: bin/magento
============ 5. CLEAR CACHES ETC ============
Could not open input file: bin/magento
Could not open input file: bin/magento
----------------------------------------------
========== 6. INSTALL FLAG COMPLETE ==========
----------------------------------------------
Could not open input file: bin/magento
```

Can you give me any advice on how to solve this?

**Comment by collymore** [comment]
Hi @robhuijben 
The nginx remaining on  * Starting nginx nginx   , is fine and you should just leave that terminal open and nginx will be running. If you check the Ports tab you should see, "Magento - Nginx (8002)", this is the port nginx is running, opening your workspace url in a browser with 8002- prefixed should show you the Magento application. 

Could not open input file: bin/magento, this is an error and needs fixing, did you make changes to the gitpod/m2-install.sh?
You may have accidentally broken something, can you share that file with me?
